# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "v6.1" branch
  push:
    branches: [ "v6.1" ]
  pull_request:
    branches: [ "v6.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    env:
      AUTOIT_VERSION: v3.3.18.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Cache AutoIt
      id: cache-AutoIt
      uses: actions/cache@v4
      with:
        path: "C:/Program Files (x86)/AutoIt3/"
        key: autoit_${{ env.AUTOIT_VERSION }}-${{ runner.os }}

    # Runs a single command using the runners shell
    - name: Install AutoIt
      if: steps.cache-AutoIt.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://www.autoitscript.com/autoit3/files/archive/autoit/autoit-${{ env.AUTOIT_VERSION }}-setup.exe -OutFile autoit-v3-setup.exe
        ./autoit-v3-setup.exe /S

    # Runs a single command using the runners shell
    - name: patch & build
      shell: cmd
      run: |
        sed -i -e '/^#pragma /s/!github_sha!/${{ github.sha }}/' source/Portable-VirtualBox.au3 |bash
        build.bat

    # Runs a single command using the runners shell
    - name: zip
      shell: cmd
      run: |
        cd build/source/Portable-VirtualBox
        7z a -tzip ../../../Portable-VirtualBox.zip *

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Portable-virtualbox_build_${{ github.sha }}
        path: build/source/Portable-VirtualBox/**

    - name: Create release with gh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: "actions-build"
        FILE: "Portable-VirtualBox.zip"
      shell: bash
      run: |
        if gh release delete "${TAG}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag --yes; then
          echo "gh release delete ${TAG}"
        else
          echo "No existing release to delete"
        fi
        gh release create "${TAG}" "${FILE}" \
          --title "actions-build" \
          --notes "Automated build from GitHub Actions" \
          --prerelease \
          --target "${GITHUB_SHA}" \
          --repo "${GITHUB_REPOSITORY}"
